### ISSUE TITLE
Is it supposed to work with neovim 0.5.1?

### ISSUE THREAD

**Issue by alex3kov** [paretje/nvim-man#1]
I installed the 0.1.0 tag tarball, getting `E117: Unknown function: man#open_page` on `:Man printf` command.

**Comment by paretje** [comment]
The 0.1 tag predates the fork, i.e. it's from the original project. I created a new tag. master and 0.2.0 should work, I'm using it with neovim 0.5.1 myself.

**Comment by alex3kov** [comment]
Thanks for following up. v0.2.0. doesn't work either for me, different error:
```
Vim(let):E117: Unknown function: man#extract_sect_and_name_ref
```

**Comment by paretje** [comment]
I just pushed a fix for this.
